// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Pq8-52QZbpPrJT_VMI5RZAJ5NiNTxz0',
    appId: '1:855811112189:web:0d10bfeba3b07828e9d294',
    messagingSenderId: '855811112189',
    projectId: 'test-57d8d',
    authDomain: 'test-57d8d.firebaseapp.com',
    storageBucket: 'test-57d8d.appspot.com',
    measurementId: 'G-YVFVXHG899',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEIOkwZWppr2TaqKwvoYH6awgE1BEgIms',
    appId: '1:855811112189:android:fa7ed57723e4ae5de9d294',
    messagingSenderId: '855811112189',
    projectId: 'test-57d8d',
    storageBucket: 'test-57d8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKE3hs9sz6kcDXf4ao3Hw4puma-lXDRpQ',
    appId: '1:855811112189:ios:18b03dd7c08c6449e9d294',
    messagingSenderId: '855811112189',
    projectId: 'test-57d8d',
    storageBucket: 'test-57d8d.appspot.com',
    iosClientId: '855811112189-ntbl60t8b8d9pjmegph4cvr544j5n1pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.yanal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKE3hs9sz6kcDXf4ao3Hw4puma-lXDRpQ',
    appId: '1:855811112189:ios:18b03dd7c08c6449e9d294',
    messagingSenderId: '855811112189',
    projectId: 'test-57d8d',
    storageBucket: 'test-57d8d.appspot.com',
    iosClientId: '855811112189-ntbl60t8b8d9pjmegph4cvr544j5n1pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.yanal',
  );
}
